# Generated by Django 3.2.16 on 2023-01-31 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='entry_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting approval'), (1, 'Published')], default=0),
        ),
    ]
